### ISSUE TITLE
rxdart 0.18.0にupdate

### ISSUE THREAD

**Issue by shrek-kurata** [sensuikan1973/Flutter_RxDart_GetStarted#1]
こちらflutter run したところ、rxdart updateしないと怒られました

**Comment by sensuikan1973** [comment]
rxdart もう `0.20.0` まできているのですね。
修正しておきます。

**Comment by sensuikan1973** [comment]
https://github.com/sensuikan1973/Flutter_RxDart_GetStarted/commit/aee46d4e9ba2f123a085f0068ae336f2632f1000
